language: java
jdk:
  - openjdk8
addons:
  ssh_known_hosts: 39.106.167.190
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
before_deploy:
        - openssl aes-256-cbc -K $encrypted_137f45644142_key -iv $encrypted_137f45644142_iv
          -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script:
  skip_cleanup: true

